### ISSUE TITLE
Install instructions for spacemacs

### ISSUE THREAD

**Issue by paynito** [narendraj9/hledger-mode#11]
Hi, I couldn't figure out how to edit your wiki. I added some instructions here.  https://github.com/paynito/hledger-mode/wiki/Getting-Started-on-Mac---Spacemacs

**Comment by narendraj9** [comment]
@paynito Do you want me to add the instructions to this wiki? Why couldn't you do it?

**Comment by paynito** [comment]
Yes, you can add them.  I don't know, I can't find the edit button. Maybe there is a setting on your wiki that is set to owner only or something?

**Comment by narendraj9** [comment]
@paynito I think it's fixed now. If you get the time to, you can try this again. :) For now, I will add your instructions.
