### ISSUE TITLE
Missing -pkg.el file

### ISSUE THREAD

**Issue by YoungFrog** [narendraj9/hledger-mode#15]
There's no hledger-mode-pkg.el file.  IIUC Melpa creates one for us but it seems broken (see also https://github.com/melpa/melpa/issues/4680).

That's the generated file:

> (define-package "hledger-mode" "20170402.1110" "A mode for writing journal entries for hledger."
>   '((emacs "24.4")
>     (popup "0.5.3")
>     (async "1.9")
>     (htmlize "1.47"))
>   :url "https://github.com/narendraj9/hledger-mode.git" :keywords
>   '("data"))

Note how it does not mention emlib, which _is_ required by hledger-suggest.el. This leads to a compilation failure when installing hledger-mode without emlib installed.

I believe a proper -pkg.el file should be committed to the repo.

**Comment by narendraj9** [comment]
@YoungFrog Thanks for pointing this out. We do not need `emlib` so far. I will remove the `require`. Will commit a pkg.el when I have time. A pull request is welcome! :)

**Comment by purcell** [comment]
No, please don't add a `pkg` file. Just put the metadata in your main `.el` file, and we'll continue to generate it for you. :-)

**Comment by YoungFrog** [comment]
Oh I had not spotted the data was in the main file. So that's how it works. Well, as long as the package is only distributed via melpa, there's no other reason to add a -pkg file I guess.

**Comment by narendraj9** [comment]
@purcell Thanks :)

**Comment by purcell** [comment]
> Well, as long as the package is only distributed via melpa, there's no other reason to add a -pkg file I guess.

Even if you want to distribute the package elsewhere, you can just use `cask` with its `package-file` directive to generate the `-pkg.el` file in the same way that MELPA does it. :-)
