### ISSUE TITLE
Provide melpa-stable package

### ISSUE THREAD

**Issue by markokocic** [narendraj9/hledger-mode#21]
Please provide a stable package version available on melpa-stable.

**Comment by narendraj9** [comment]
@markokocic Glad that you are using this package. I will try to get this done during the weekend. Not sure if `melpa-stable` has some strict requirements.

**Comment by markokocic** [comment]
@narendraj9 actually I wanted to give it a try, but I don't use melpa, just melpa-stable.

I don't think it has any strict requirements except that it's considered as a stable release by package author, and that it works with other stable package dependencies.

**Comment by narendraj9** [comment]
@markokocic You can try it out by cloning the repository and adding the path to this repository to your `load-path` (if you think that's convenient) until it it added to `melpa-stable`. Do let me know if you face any issues.

**Comment by narendraj9** [comment]
No longer planning to make any new changes.
