### ISSUE TITLE
exec-path issue. zsh:1: command not found: hledger

### ISSUE THREAD

**Issue by firmart** [narendraj9/hledger-mode#29]
I've installed `hledger` in `~/<user>/.local/bin/` :
```
$ hledger --version                                    
hledger 1.15.2
$ where hledger 
/home/<user>/.local/bin/hledger
```

Doing `hledger-run-command` gave me `zsh:1: command not found:` in the report buffer.

Here is the relevant configuration : 
```emacs-lisp
(add-to-list 'exec-path "/home/<user>/.local/bin")
;; ...
(use-package hledger-mode
:ensure t
:mode ("\\.journal\\'" "\\.hledger\\'")
:init
(setq hledger-jfile "~/personal/accounting.journal")
```
and the weird part is if I `eval-expression`
```emacs-lisp
(executable-find "hledger")
```
I get
```
"/home/<user>/.local/bin/hledger"
```

If I move all `hledger-*` binaries in `/usr/bin`, all command work fine. I'm missing something, 
how should I specify the binary's path ?

**Comment by narendraj9** [comment]
Hi! Sorry for replying late to the issue. Can you please share the report you were trying to create?

**Comment by firmart** [comment]
Sorry, seems that I can't reproduce it anymore. Maybe it was a `$PATH` issue..
