### ISSUE TITLE
flycheck-hledger

### ISSUE THREAD

**Issue by DamienCassou** [narendraj9/hledger-mode#36]
I just created [flycheck-hledger](https://github.com/DamienCassou/flycheck-hledger). You might want to try it and/or reference it in your README.

**Comment by narendraj9** [comment]
Hey @DamienCassou , thank you for sharing this. It will be useful for me and other `hledger-mode` users. Please feel free to add a change mentioning it.

**Comment by DamienCassou** [comment]
See PR #37.
