### ISSUE TITLE
appendig currency string

### ISSUE THREAD

**Issue by muralikodali** [narendraj9/hledger-mode#39]
i am using the currency symbol ( INR ) to append after value.
my ledger file is three years old.

setting (setq hledger-currency-string "INR") is prepending INR before value.
can we change this behaviour ?
```
expected : 

2021-12-20  purchase of rice
     Assets:Current:Cash       20.00 INR
```

```
what is happening : 

2021-12-20  purchase of rice
     Assets:Current:Cash       INR 20.00
```

**Comment by narendraj9** [comment]
You can try adding this to your `init.el`: 

```lisp
(defun hledger-indent-account-line* ()
  "Called when the line to indent is an account listing line."
  (cond
   ((hledger-cur-line-matchesp (concat hledger-whitespace-account-regex "\\s-*" hledger-amount-value-regex))
    (insert " INR"))

   ((hledger-expecting-rupeep) (insert "    "))

   (t (indent-line-to tab-width))))

(advice-add 'hledger-indent-account-line :override #'hledger-indent-account-line*)
```

A general solution that makes it customizable will take some time and I don't plan to do it in the near future. If the above workaround doesn't work for you, let me know. :)

**Comment by muralikodali** [comment]
thanks

now currency symbol is getting appended after value
