### ISSUE TITLE
Exclamation point status prevents indention.

### ISSUE THREAD

**Issue by reteo** [narendraj9/hledger-mode#40]
When I attempt to use the exclamation point as a status mark (pending transactions), the next line (the first account adjustment) does not indent until I fill it in completely.

You can work around this; once you finish typing the first line (including the number) and press \<Tab\>, the line will then indent properly.

**Comment by narendraj9** [comment]
It can be fixed by changing the regex we use for the first line of an entry to something like this: 

```elisp
(setq hledger-date-and-desc-regex (format "\\<%s\\s-*[\\*!]?\\s-*[^[:space:]]+\\>" hledger-date-regex))
```

Does adding this or just evaluating this after `hledger-mode` is loaded, fixes your problem?

**Comment by reteo** [comment]
I tried it, but I get the following error:

```
Symbol's value as variable is void: hledger-date-regex

```

I suspected that the `hledger-date-regex` was supposed to be `'hledger-date-regex`, so I tried that, which averted the error.  However, that didn't have an effect. on the end result.

**Comment by narendraj9** [comment]
Thanks for the update, I have merged the fix for this: https://github.com/narendraj9/hledger-mode/pull/42 :)
