### ISSUE TITLE
error on keybinding

### ISSUE THREAD

**Issue by Abu-Daud** [narendraj9/hledger-mode#44]
hello.  I tried your keybinding
`  (global-set-key (kbd "C-c j") 'hledger-run-command)
`
it produces this error

`command-execute: Wrong type argument: commandp, hledger-run-command
`

same error if I use
` (spacemacs/set-leader-keys "hbb" 'hledger-run-command)
`
` (spacemacs/set-leader-keys "hbb" 'hledger-balancesheet)
`
or
` (spacemacs/set-leader-keys "hbb" 'hledger-balancesheet*)
`

Thank you for this great project.  I find it useful.

**Comment by narendraj9** [comment]
This https://github.com/narendraj9/hledger-mode/commit/07baa57017e1b7703560363a6e1948b630a5158d should fix it. Or you can add `(require 'hledger-reports)` in your Emacs config before using `hledger-run-command`.
