### ISSUE TITLE
Need advice on making hledger completion work with Corfu/capf

### ISSUE THREAD

**Issue by ghoseb** [narendraj9/hledger-mode#45]
Hi, I need some advice on making auto-completion work with Corfu. Corfu, unlike Company uses the built-in cap functions. I can see that the docs mention using Company and auto-complete, but it's not clear how to make it work with Corfu. Any advice will be appreciated. Thanks.

**Comment by narendraj9** [comment]
Hi BG, 

I tried the following as a `completion-at-point` function: 

```emacslisp(defun hledger-completion-accounts ()
  (when-let ((bounds (and (boundp 'hledger-accounts-cache)
                          (bounds-of-thing-at-point 'symbol))))
    (list (car bounds) (point) hledger-accounts-cache)))

(add-hook 'hledger-mode-hook
          (lambda ()
            (add-hook 'completion-at-point-functions 'hledger-completion-accounts)))

```

It's possible to maybe filter out non-matching accounts directly in the `completion-at-point` function but the rest of the completion framework (using `try-completion`) seems to be doing that as well. 

Let me know if it works for you. :)
