### ISSUE TITLE
`hledger-update-accounts` not working

### ISSUE THREAD

**Issue by felipeqq2** [narendraj9/hledger-mode#59]
When using `hledger-mode` with company support, I noticed that the `hledger-accounts-cache` was never filled up. I traced the issue back to this:

---

When running `(hledger-update-accounts)` on a journal file, it throws `Wrong type argument: stringp, nil`. A buffer must be specified for the function to work, even though it's marked as an optional argument, and is used without an argument throughout the code. Therefore, `hledger-accounts-cache` is never set.

I guess the function was supposed to default to the `current-buffer` if no argument is provided, but it currently runs the function _only_ if the buffer is `nil` or equal to `current-buffer`:
https://github.com/narendraj9/hledger-mode/blob/1b9c65298c34933d6667773d7fa1e89c9841038d/hledger-defuns.el#L346-L349

**Comment by shivjm** [comment]
Thanks for the report, and as the person responsible for these functions, I apologize for the trouble. I’m not currently able to reproduce this behaviour. If I run `(hledger-update-accounts)`, it completes without issue. I think I need to try again with a pristine version of hledger-mode, though. May I ask which revision of hledger-mode and which version of Emacs you’re using?

I’m also unable to spot where the buffer is mandatory in the code; both `hledger-update-accounts` and `hledger-get-accounts` work fine without a buffer specified, at least in my testing as well as if I follow the logic. Even though `hledger-update-accounts` unconditionally passes `buffer` to `hledger-get-accounts`, the latter only uses it if it’s non-`nil`.

**Comment by felipeqq2** [comment]
Hey, thanks for the fast response! Sorry for pointing you in the wrong direction :grimacing:. This issue only happens when `hledger-jfile` is `nil`. I don't think this is an obvious issue, so I'm closing it for now.

**Comment by shivjm** [comment]
Ah, I see. Well, the best problems are the ones that solve themselves!
